ci:
  autofix_prs: true
  autoupdate_schedule: weekly
  autofix_commit_msg: "fix(pre_commit): 🎨 auto format pre-commit hooks"
  autoupdate_commit_msg: "chore(pre_commit): ⬆ pre_commit autoupdate"

repos:
  -   repo: https://github.com/psf/black
      rev: 23.9.1
      hooks:
      -   id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)


  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: Flake8 Checks
        entry: flake8
        additional_dependencies: [Flake8-pyproject]